### ISSUE TITLE
Staleness/Increment not working as expected

### ISSUE THREAD

**Issue by mitchmastroni** [dhowe/dialogic#31]
Steps to Reproduce: Parse this set of Chats, repeatedly pass a ResumeEvent with parameters {type=test}
```
CHAT CORE_Stale_Slow {type=test, stage=CORE, stalenessIncr=0.05}
SAY slow!

CHAT CORE_Stale_Med {type=test, stage=CORE, stalenessIncr=1}
SAY medium!

CHAT CORE_Stale_Fast {type=test, stage=CORE, stalenessIncr=20}
SAY fast!
```

Expected: CORE_Stale_Slow will appear with increasing frequency, CORE_Stale_Fast will appear with decreasing frequency.

Actual: All three chats appear at the same frequency. In fact, after all three have played, they repeat that same pattern infinitely.

**Comment by dhowe** [comment]
This is intended behavior. In a conversation with DC earlier this week we decided to try using lastRunAt time to break ties in Find searches. This use-case however makes it clear that this is not what we want after all. So, I've replaced the tie-breaking behavior to again be sort by points, then (if tie) staleness, then (if tie) coin-flip. We may want to add lastRunAt time as a 3rd tie-breaking criteria before the coin-flip, but I'll leave that as a question for later. In any case, you should now get the expected behavior above.

**Comment by dcannizzaro** [comment]
I think the problem isn't the tie breaking, which we discussed not using staleness, but the fact that staleness doesnt seem to be affecting the find's at all.

My understanding is that the staleness should limit the pool of possible results.  so that after the chat with the stalenessIncr=20 plays, it'll become very stale and will then not show up in the search results for a while so there will be no tie to break.  

We last discussed having dialogic store and relax the staleness threshold per 'find'  Is there something we need to do on the unity implemntation side to make use of this behavior?

**Comment by dhowe** [comment]
Yes, that is correct -- there are actually a few issues at play here. One is that the default staleness for Finds was not getting set correctly for Finds created via ResumeEvents, rather than via the parser (this should now be fixed. To specify a Find staleness threshold other than the default, you can just pass it in metadata: `Find {type=test,staleness<5)` (notice that it should be < or <=). If no Chats are found with that constraint, it will be gradually relaxed until one is found. However, this relaxation is _not_ persistent; by this I mean  that the next time that same Find is run, the threshold will start again at 5 (let me know if such persistence is something we want). And all of these issues are indeed orthogonal to the tie-breaking strategies (thanks DC for pointing this out), any of which should probably work ok with the fix above in place.

**Comment by dcannizzaro** [comment]
That makes sense.  We probably do want to make the relaxation persistant per Find, otherwise it will have to do a lot of extra searches  and relaxations each time, once the chats matching that find's criteria become stale.  Though behavior wise it probably is the same effect so that's probably a performance optimization.  Is there a default value it relaxes the staleness criteria by each time?  is that just equal to the default stalenessIncr value of 1?

**Comment by dhowe** [comment]
Yes, that seems just a performance optimization, which I will add an issue to address later... So far the relaxation has been happening at .5 increments, though this can now be set via Defaults.FIND_RELAXATION_INCR
